### ISSUE TITLE
[Crash] [Neo] Lunar - Loading in pre-existing world causes crash

### ISSUE THREAD

**Issue by Cixon** [TathanDev/SkyAesthetics#10]
## Latest Log (line 1432)
[latest.log](https://github.com/user-attachments/files/17350858/latest.log)

## Crash report
[crash-2024-10-12_12.21.59-client.txt](https://github.com/user-attachments/files/17350862/crash-2024-10-12_12.21.59-client.txt)

## Resource-pack
[Beta Stars.zip](https://github.com/user-attachments/files/17350870/Beta.Stars.zip)

**Comment by Cixon** [comment]
> ## Resource-pack
> [Beta Stars.zip](https://github.com/user-attachments/files/17350870/Beta.Stars.zip)


Crash occurs when loading RP. Very odd.

**Comment by TathanDev** [comment]
So I had added better compat to Lunar like size changing depending of the event or vibrant color but it seems to crash the mod
so now it just work.

Enjoy the mod !
(the new version is available)

**Comment by Cixon** [comment]
works wonderfully. thank you so much!
