### ISSUE TITLE
[bug] sunrise_color - does not work, unsupported feature?

### ISSUE THREAD

**Issue by Cixon** [TathanDev/SkyAesthetics#12]
## This bug exists for NeoForge 1.21.1 (1.2.5)
![2024-11-07 17_21_43-Greenshot](https://github.com/user-attachments/assets/940ec1c8-f5c0-43ee-bd48-21ca756c52bb)

# To test, I made the sunrise color white (FFFFFF) or converted to decimal (16777215)

**Comment by Cixon** [comment]
### RP to test:

[Beta Stars.zip](https://github.com/user-attachments/files/17670660/Beta.Stars.zip)

**Comment by TathanDev** [comment]
thanks for the report I'll check !

**Comment by Cixon** [comment]
thanks !

**Comment by TathanDev** [comment]
This will be in the next update that should be soon !

**Comment by TathanDev** [comment]
New version out now : https://modrinth.com/mod/sky-aesthetics !
