### ISSUE TITLE
[1.21.1] v1.2.7 Crashes on world startup

### ISSUE THREAD

**Issue by Cixon** [TathanDev/SkyAesthetics#13]
Not sure why this happens

Latest log (ln 1487):
[latest.log](https://github.com/user-attachments/files/17788587/latest.log)

Crash:
[crash-2024-11-16_20.16.21-client.txt](https://github.com/user-attachments/files/17788590/crash-2024-11-16_20.16.21-client.txt)

**Comment by Cixon** [comment]
[testsky_lce.json](https://github.com/user-attachments/files/17788597/testsky_lce.json)

**Comment by TathanDev** [comment]
Fixed in this version https://modrinth.com/mod/sky-aesthetics/version/H12eV2Zn !

**Comment by TathanDev** [comment]
Also, I saw that value of the last float in the sunrise_color value is pretty high? It should be between 0 and 1. If it's too high, the sky will be white

**Comment by Cixon** [comment]
## Trying to replicate this sunset color:
![2024-11-06 22_05_10-Greenshot](https://github.com/user-attachments/assets/c2146fb6-6eba-4279-9e13-a451a379451c)

**Comment by TathanDev** [comment]
The sunrise color has changed in the new version (1.2.9). Now, it's need R, G and B value (it's easier)

**Comment by Cixon** [comment]
> The sunrise color has changed in the new version (1.2.9). Now, it's need R, G and B value (it's easier)

what is the format? is it on the wiki?

**Comment by TathanDev** [comment]
Yes it is https://github.com/TathanDev/SkyAesthetics/wiki/Custom-Sky
