### ISSUE TITLE
[1.2.12] Minor issue with sunset rendering - it renders at night

### ISSUE THREAD

**Issue by Cixon** [TathanDev/SkyAesthetics#14]
# Demonstration:

https://github.com/user-attachments/assets/a8b50a89-aee9-4d8a-b5f8-e5af80bc1467

**Comment by Cixon** [comment]
Occurs when the night starts and at midnight. should only render right before the night ends

**Comment by TathanDev** [comment]
Thanks for the report ! I know how to fix this !

**Comment by Cixon** [comment]
sweet, thanks for fast reply! can't wait for this fix

**Comment by TathanDev** [comment]
Fixed ! Will be in the next update
