### ISSUE TITLE
Bug: Objects Overlay the World

### ISSUE THREAD

**Issue by AlphaLeoli** [TathanDev/SkyAesthetics#3]
Idk why this happens but it went away when I took a screenshot with essential and came back as soon as the popups disappeared. I know there is a worldborder in that screenshot, but it's not the reason why (it still happens without)
![image](https://github.com/user-attachments/assets/77ebe782-d93e-4305-b63c-7d3e320ab1cc)
MC Version: 1.21.1
Mod Version: 1.0.0

**Comment by TathanDev** [comment]
Thanks for the report !
Can you send me the modpack/mod list that you used ?

Thanks !

**Comment by AlphaLeoli** [comment]
wait i think it was fabricskyboxes bc i removed it and it works now. though i didn't even have any pack on that used it so idk why
