### ISSUE TITLE
[Suggestion] A dedicated mod to utilize this normally with JUST a resource pack?

### ISSUE THREAD

**Issue by Cixon** [TathanDev/SkyAesthetics#7]
I find this mod to be a bit misleading, figured if I made changes in a RP, reloaded textures, I would see changes but nothing... I don't understand?

I now know it's a API but perhaps a separate mod could make it more viable for RP creators? That's it. Thanks!

**Comment by Cixon** [comment]
For example, I want to replicate the Beta Skies where the stars are huge. This mod would have been perfect for my NeoForge modpack but unfortunately, there's nothing I can do to emulate this in the Overworld.

**Comment by Cixon** [comment]
> What is the difference between when you integrate it with your modpack and when you add it with a datapack. Everything is configurable with datapack (and only with datapack)


what do u mean, the resourcepack don’t work. you could send a example .zip and i’ll load it and nothing changes…

**Comment by TathanDev** [comment]
So it's the reload or just the resourcepack that don't work ?

**Comment by Cixon** [comment]
> So it's the reload or just the resourcepack that don't work ?

I utilized the assets provide in the .jar. I made an attempt to load them but nothing happened so I tried to make my own changes by changing the ID of the big_dipper.json to just big.json and this did nothing. Am I suppose to accommodate the resourcepack with a datapack? If so, can you please provide an example .zip or a guide?

**Comment by TathanDev** [comment]
You just need to create a resourcepack and play with the mod installed

**Comment by Cixon** [comment]
> You just need to create a resourcepack and play with the mod installed

can u provide a functional 1.21.1 RP for me to use please

**Comment by TathanDev** [comment]
[resourcepacks.zip](https://github.com/user-attachments/files/17296416/resourcepacks.zip)
This works for me

**Comment by Cixon** [comment]
> [resourcepacks.zip](https://github.com/user-attachments/files/17296416/resourcepacks.zip) This works for me ![image](https://private-user-images.githubusercontent.com/67022946/374646919-b651314f-44c5-4412-941b-024743b2e60e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDE5NTksIm5iZiI6MTcyODQ0MTY1OSwicGF0aCI6Ii82NzAyMjk0Ni8zNzQ2NDY5MTktYjY1MTMxNGYtNDRjNS00NDEyLTk0MWItMDI0NzQzYjJlNjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAyNDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZDkwMDFmNDAzZjEyOTllNTQ0MTQ5NDdmZjdhODVkOGFiOTMwYTVjOTdhZDY5OGUwZjVkN2NjNTZkOGEwMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m8z04XJHrQCD_xpSC05Es7pxUyoWvzi7oVGiPBU0eQw)

Thank you for this, it was a user misinput. I apologize... just gotta figure out how to make it look like Beta Minecraft stars now. Thank you all for your patience with me, LOL!

**Comment by Cixon** [comment]
anyone know the default sun and moon height and sizes?
