### ISSUE TITLE
[bug] Sky data does not unload when removed from RP list.

### ISSUE THREAD

**Issue by Cixon** [TathanDev/SkyAesthetics#8]
### Demonstration

https://github.com/user-attachments/assets/65dc828b-aba7-4d72-a674-9372e3fb3fe8

Made attempt to switch to a different assort that should in theory, remove it as a loaded RP.
This did not unload the custom Beta Stars despite the default assort not having it listed on their...

**Comment by Cixon** [comment]
As of rn, in order to remove the custom changes to the skie, the user will need to reload their client entirely.

This bug exists for NeoForge 1.21.1

**Comment by TathanDev** [comment]
Fixed in the new update (1.2.3)
