### ISSUE TITLE
[Mod-incompat] Why no option to disable custom_vanilla_objects?

### ISSUE THREAD

**Issue by Cixon** [TathanDev/SkyAesthetics#9]
We're able to opt out of "sky_color" changes by using `"custom_color": false` well, why not for sun and moon?

I ask because my modpack uses [Lunar](https://modrinth.com/mod/lunar) which adds custom moons and though, the mod still works, it will never display the custom moon visuals. If only there was a option like `"use_custom_vanilla_objects":false`

Issue exists for all versions but I use Sky Aesthetics 1.2.3 [NeoForge].

**Comment by Cixon** [comment]
I could be misinformed as I'm new to this mod. I really only take advantage of the star mechanics which is beautiful, great work on this! I hope there's a way I could use Lunar's moon visuals with Sky Aesthetics soon.

**Comment by Cixon** [comment]
> If only there was a option like `"use_custom_vanilla_objects":false`
 
or just a option to just do something like `"use_vanilla_moon":true` and `"use_vanilla_sun":true`, defaulted as `false` so that way, anyone who has a RP, it won't ruin it.

**Comment by TathanDev** [comment]
You can download the new version here : https://modrinth.com/mod/sky-aesthetics/versions
